---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  provider:
    vault:
      server: "https://vault.local.zachary.day"
      path: "secret"
      version: "v2"
      auth:
        jwt:
          path: "PATCH_ME"
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: "vault-sa"
            audiences:
            - vault
            expirationSeconds: 600