---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bitwarden-ca-issuer
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-ca-certificate
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
spec:
  # this is discouraged but required by ios
  commonName: cert-manager-bitwarden-tls
  isCA: true
  secretName: bitwarden-ca-certificate
  subject:
    organizations:
      - external-secrets.io
  dnsNames:
    - external-secrets-bitwarden-sdk-server.external-secrets.svc.cluster.local
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: bitwarden-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bitwarden-server-issuer
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  ca:
    secretName: bitwarden-ca-certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
    - external-secrets-bitwarden-sdk-server.external-secrets.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: bitwarden-server-issuer
    kind: Issuer
    group: cert-manager.io